{% set version = "0.18.0" %}

package:
  name: djangorestframework-gis
  version: {{ version }}

source:
  url: https://github.com/openwisp/django-rest-framework-gis/archive/v{{ version }}.tar.gz
  sha256: 4d99d400262f8dd2d24fe634f66f0b967c18fe2db12a5cf88f82781960cd9e09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - djangorestframework >=3.10
  run:
    - python >=3
    - djangorestframework >=3.10
    - django >=2.2

test:
  imports:
    - rest_framework_gis

about:
  home: https://github.com/djangonauts/django-rest-framework-gis
  summary: Geographic add-ons for Django Rest Framework
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/djangonauts/django-rest-framework-gis
  dev_url: https://github.com/djangonauts/django-rest-framework-gis

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
