{% set name = "djangorestframework-gis" %}
{% set version = "0.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-gis-{{ version }}.tar.gz
  sha256: 6ddd201a208e68f8f11ac71d2df2c030b1280818a4b54681be00e73057fcafb1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - djangorestframework >=3.10
    - django >=2.2

test:
  imports:
    - rest_framework_gis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/djangonauts/django-rest-framework-gis
  summary: Geographic add-ons for Django Rest Framework
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/djangonauts/django-rest-framework-gis
  dev_url: https://github.com/djangonauts/django-rest-framework-gis

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
