{% set version = "0.12" %}
{% set sha256 = "80f5e024079f23421c7a34123eb0f50e8a324a61fc1366ed0173aa1a89d766a7" %}
{% set build = 0 %}

package:
  name: djangorestframework-gis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-gis/djangorestframework-gis-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - djangorestframework >=3.3

  run:
    - python
    - djangorestframework >=3.3

test:
  imports:
    - rest_framework_gis

about:
  home: https://github.com/djangonauts/django-rest-framework-gis
  summary: 'Geographic add-ons for Django Rest Framework'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/djangonauts/django-rest-framework-gis
  dev_url: https://github.com/djangonauts/django-rest-framework-gis

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
