{% set version = "0.14" %}

package:
  name: djangorestframework-gis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-gis/djangorestframework-gis-{{ version }}.tar.gz
  sha256: e645c6c8aedee53ac0a4851abcdf8121fff66813eebae1b040b1ccb941cb248b

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - djangorestframework >=3.3

  run:
    - python
    - djangorestframework >=3.3

test:
  imports:
    - rest_framework_gis

about:
  home: https://github.com/djangonauts/django-rest-framework-gis
  summary: 'Geographic add-ons for Django Rest Framework'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/djangonauts/django-rest-framework-gis
  dev_url: https://github.com/djangonauts/django-rest-framework-gis

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
