travis:
  secure:
    BINSTAR_TOKEN: SFhPjoOPOU78uRD9Bu+XgMKmunnZXLGrSE3kdPOVwR08jjuHHrk9N4dVkHTrENX2Fn0WS5K/ou0mTxErPU24WJOORhTn+VXWTWmYUXu9gxNlhSIx8lW7weuCuZRNWBint4QKBa/2VARvjIUnGgP+Nz4S+aqsakoi4aWygInMdd33oTvsKc41pyin7EviFQs2oUTPToY6vNRh4bOT3OIr/MQq5DQDlxxsZK9t/mptBYTV6+tH7+75Ke8jnWYkw7miRDdSs6UM+z5O8M0W/w7jNipaImcShvzecC7mNsCSvi8b95cMTNuy0ZEVmkJERL0Ls6O3grmA6fc+OT5jPQ8BGYJGv9j2TSwWYTDwVVDNfHWrDK0m4rHJcJ7uCAbsfTPKt76xEnTRITIgW9BR9VYlLXFj59+U9ZGoolU4oiNso0P1f+eJ9DTwKB2D8yy6SHmY48upLyZJ7Er2HhlO3CPEwmz5QcTETrNuC1RyCw/H6G1wipd4IZQmYPBr7KgeXqFKz2mtRhlOGIvuu5URAaY+vLKCp7Q8qA5NoGqHJ/QU6bdP0B70gUOOa1znr6H2Z266/Vuiw+Dlq6PcvUBFiBqf5aG+n/c4die8AG6yCuwF9dHiqRcoTMvCC3eGohKjg71ZBCOuRLv0PDU6cxBpgnA+LzvPHA51PvhU5TSB14Ofn94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
