travis:
  secure:
    BINSTAR_TOKEN: N2MwsZ0RxYBb8RKn1/RPTtw6lvMqVLmFOWWsmYWqP/URsDGOw8RJso9ay1fyOLMXCIc94HEmcirlWOLKjNpwraVRwUNgxQxIshYmQx9iaSrytHNpqyL7zBTSn+wZK2jrqlSHqRe1wCGlWr2lQXgGMbjcfk4837GB3EHYIOMmLjwcJErp73BYUjw23QkB7gy5YsXffbL9gX/txzJGril8zsWbQajjDjwXMHi+FZ66Lv0SHKhsC2TFeCI82cR9c8osAPrEPSjTC8sB6j2FNkbUCo33icaWPZ83r3Gm+kb057jIvVetMMeLXh9kQfbmvOITj4HVF1Nvag8tQU/sXy0CgqMIvluHNFURzITGIO3ZxsyFAOSSYlWoW7LVUi1MLdLM3Q+mTkhgaRh+RXhzPEdT23xmRr9Yto+zGxqB2BHj3iPLU+yW9lJkgkHrhi6ixCmDsgp7RT3gV+c3HbIcpVgWa5RpTvO7Et3tl4R4/FtbQuYmH1kihmAmoSuxwAfUMkYLLQV4c2BEtE3pDl7Spk7pFS1Il+wLNLPZ4T1yLyfObrF5t1TFrPDb39ONgmNsDtpKkMlxpRQdoy4gBTz7gORB/o+JQDFRyse1NzcO2DBppqmWwH9dsUCzc4imqzhwUHkNG9xg7/jUhd4unW5ZTuyLzWxXsBiYkIILjz0GA8sNkIY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
