travis:
  secure:
    BINSTAR_TOKEN: ousCuKnvPCF3dLWiowsisjtquvYfwr7n//dHnWdUfNyFlQSNGJPUi2NKp9/6ybJyl+2xBk09+ebvh2WBObtIbAo6IDWpi7aB8aU/O++f3sWqzqDOPZ4jHI1OzRpfdNcnF54HEhMd6ew+HDXHWnAstcYW76+1/Mo5WCEA1TWMxm+dxd6ZsaAqWxxSXeowEAC2g4o+KSJOTYLo9SEFrR4tFsQzk4oV/R5rUwlLitPmQY+eZJ+YP7M1NL8sAgHk9/594rE00ItedHakC2w4te0BS7U/cE09icdrQfchdsUdHEPPUGxEfjJGoCnahCX2bFTMQVQOJ4SwPiggvZLaoax/iBd4V0WrA4xP7kSNner6NQkEjUQ+s1IIN8Iwc4qA+Ced6mXlV9XJ4pmtOYFRQ8AtMiM1UHtItaY5oW6TF+bOBid0Y3nc37JAJsnlf8zNoHSYI2F0sWoT85gmsHGBG+jHxHNH95iDzlDFFf+wBgYPT7aelvJ1EAKaVdj9K9KQttp04uho1u6/kJ5AWmVC4cr8rcnb8GIjz8/qFYyFc595sEq3p34jhOTPU7DSZwOxDFCLSkEH8s3kID75WVJW3Yq787Cpcv4pyrxo+vA4L4NYM07Yr+lfZ0YCmPvlwx/sjenM7ldJCTaH2zsMTDCT3iFh4k1SWtc/+top8pu6SkdBmzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
